#!/bin/bash
pyrun $HOME/Downloads/openttd/nml-0.4.5/nmlc -c -p DEFAULT --clear-orphaned wannaroo-all-engines-all-climates.nml
cp -i wannaroo-all-engines-all-climates.grf $HOME/.openttd/newgrf/wannaroo-all-engines-all-climates.grf

